### ISSUE TITLE
How to manage vimrc files

### ISSUE THREAD

**Issue by hbetts** [hbetts/dotfiles#1]
Can I break the large `.vimrc` file into more manageable, purpose-driven, smaller, files?

**Comment by hbetts** [comment]
@courtnek, do you have any thoughts on this?

**Comment by courtnek** [comment]
@hbetts I'm for it, although it might be worth clarifying 'purpose-driven'.

I have my vimrc currently [seperated into folds](https://github.com/courtnek/dotfiles/blob/master/vim/vimrc.symlink#L126), which I'm not thrilled with.

Each fold could easily be separated into a different file (the current plan). For me, this means sets of alike settings such as 'status line' modifications, CtrlP variables, Powerline Setup, etc.

I know we previously talked about 'workflow' driven categories, such as JS stuff in one file C++ in another, etc. I assume that would also have a common vim file somewhere for stuff that applies to all? Like remapping your <Leader>?

**Comment by hbetts** [comment]
@courtnek, what I meant by _purpose driven_ was that I would like to group key mappings, plugin settings, and utility methods, based on whether it's related to C++ development, JavaScript development, third-party platforms, etc.

**Comment by courtnek** [comment]
@hbetts I took a stab at it in [this commit](https://github.com/courtnek/dotfiles/commit/67145199b404bdcffa0ec0b9de357773a18f5027)
